// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.173
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ProjectTaskRunner
{
    static class Vsix
    {
        public const string Id = "ec768980-f2de-4db0-a6e2-5e57fa612ad5";
        public const string Name = ".NET Core Task Runner";
        public const string Description = "An easy and convenient way to execute any scripts defined in project.json for any type of .NET Core project";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "Mads Kristensen";
        public const string Tags = "asp.net, project.json, task runner, scripts, dnx";
    }
}
